# Generated by Django 6.0.2 on 2026-03-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('coding', 'Coding')], max_length=25),
        ),
    ]
